//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.06 at 12:51:20 PM IST 
//


package org.agromart.container.api.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.agromart.container.api.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Items_QNAME = new QName("", "Items");
    private final static QName _Item_QNAME = new QName("", "Item");
    private final static QName _Vendor_QNAME = new QName("", "Vendor");
    private final static QName _Farmer_QNAME = new QName("", "Farmer");
    private final static QName _BiddingHistory_QNAME = new QName("", "BiddingHistory");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.agromart.container.api.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemListType }
     * 
     */
    public ItemListType createItemListType() {
        return new ItemListType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link VendorType }
     * 
     */
    public VendorType createVendorType() {
        return new VendorType();
    }

    /**
     * Create an instance of {@link FarmerType }
     * 
     */
    public FarmerType createFarmerType() {
        return new FarmerType();
    }

    /**
     * Create an instance of {@link BiddingHistoryType }
     * 
     */
    public BiddingHistoryType createBiddingHistoryType() {
        return new BiddingHistoryType();
    }

    /**
     * Create an instance of {@link BiddingHistoryListType }
     * 
     */
    public BiddingHistoryListType createBiddingHistoryListType() {
        return new BiddingHistoryListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Items")
    public JAXBElement<ItemListType> createItems(ItemListType value) {
        return new JAXBElement<ItemListType>(_Items_QNAME, ItemListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Item")
    public JAXBElement<ItemType> createItem(ItemType value) {
        return new JAXBElement<ItemType>(_Item_QNAME, ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VendorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Vendor")
    public JAXBElement<VendorType> createVendor(VendorType value) {
        return new JAXBElement<VendorType>(_Vendor_QNAME, VendorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FarmerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Farmer")
    public JAXBElement<FarmerType> createFarmer(FarmerType value) {
        return new JAXBElement<FarmerType>(_Farmer_QNAME, FarmerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiddingHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BiddingHistory")
    public JAXBElement<BiddingHistoryType> createBiddingHistory(BiddingHistoryType value) {
        return new JAXBElement<BiddingHistoryType>(_BiddingHistory_QNAME, BiddingHistoryType.class, null, value);
    }

}
